version: '3'

services:
  api:
    container_name: docker-api
    build: .
    volumes:
      - .:/go/src/api
    ports:
      - "3200:3200"
    tty: true
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "-t", "60", "--", "/go/bin/app"]
  db:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: dummy-mysql
    ports:
      - "3306:3306"
