version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3200:3200"
    tty: true
    depends_on:
      - db
    security_opt:
      - apparmor:unconfined
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: mysql
    ports:
      - "3306:3306"
