version: '3'

services:
  api:
    container_name: docker-app
    build: .
    volumes:
      - .:/go/src/api
    ports:
      - "3200:3200"
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: dummy-mysql
    volumes:
      - ./db/mysql_data:/var/lib/mysql
